# Перечень volume
volumes:
  pg_data:
  # Новый volume — для статических файлов
  static:

# Перечень контейнеров
services:
  # Контейнер БД
  db:
    # Из какого образа запустить контейнер
    image: postgres:13.10
    # Файл с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Контейнер с бэкендом
  backend:
    # Собрать образ из локальной папки ./backend/
    build: ./backend/
    # Файл с переменными окружения
    env_file: .env
    # Какие контейнеры должны быть запущены до старта этого контейнера
    depends_on:
      - db
    # Тут подключаем volume к backend
    volumes:
      - static:/backend_static

  # Контейнер с фронтендом
  frontend:
    # Файл с переменными окружения
    env_file: .env
    # Собрать образ из локальной папки ./frontend/
    build: ./frontend/
    # Подключаем volume static к /frontend_static/
    volumes:
      - static:/frontend_static
    # Вместо запуска сервера выполняем команду копирования статики
    command: cp -r /app/build/. /frontend_static/

  # Контейнер gateway (новый)
  gateway:
    # Сбилдить и запустить образ, описанный в Dockerfile в папке gateway
    build: ./gateway/
    # Проброс порта с хоста на контейнер (8000 хоста → 80 контейнера)
    ports:
      - 8000:80
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles
    # gateway должен стартовать после backend
    depends_on:
      - backend